apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-serverapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-serverapp
  template:
    metadata:
      labels:
        app: superexec-serverapp
    spec:
      containers:
        - name: superexec-serverapp
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "serverapp"
            - "--appio-api-address"
            - "superlink:9091"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-1
  template:
    metadata:
      labels:
        app: superexec-clientapp-1
    spec:
      containers:
        - name: superexec-clientapp-1
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "clientapp"
            - "--appio-api-address"
            - "supernode-1:9094"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-2
  template:
    metadata:
      labels:
        app: superexec-clientapp-2
    spec:
      containers:
        - name: superexec-clientapp-2
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "clientapp"
            - "--appio-api-address"
            - "supernode-2:9095"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-3
  template:
    metadata:
      labels:
        app: superexec-clientapp-3
    spec:
      containers:
        - name: superexec-clientapp-3
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "clientapp"
            - "--appio-api-address"
            - "supernode-3:9096"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-4
  template:
    metadata:
      labels:
        app: superexec-clientapp-4
    spec:
      containers:
        - name: superexec-clientapp-4
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "clientapp"
            - "--appio-api-address"
            - "supernode-4:9097"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-5
  template:
    metadata:
      labels:
        app: superexec-clientapp-5
    spec:
      containers:
        - name: superexec-clientapp-5
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "clientapp"
            - "--appio-api-address"
            - "supernode-5:9098"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-6
  template:
    metadata:
      labels:
        app: superexec-clientapp-6
    spec:
      containers:
        - name: superexec-clientapp-6
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "clientapp"
            - "--appio-api-address"
            - "supernode-6:9099"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-7
  template:
    metadata:
      labels:
        app: superexec-clientapp-7
    spec:
      containers:
        - name: superexec-clientapp-7
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "clientapp"
            - "--appio-api-address"
            - "supernode-7:9100"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-8
  template:
    metadata:
      labels:
        app: superexec-clientapp-8
    spec:
      containers:
        - name: superexec-clientapp-8
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "clientapp"
            - "--appio-api-address"
            - "supernode-8:9101"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-9
  template:
    metadata:
      labels:
        app: superexec-clientapp-9
    spec:
      containers:
        - name: superexec-clientapp-9
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "clientapp"
            - "--appio-api-address"
            - "supernode-9:9102"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-10
  template:
    metadata:
      labels:
        app: superexec-clientapp-10
    spec:
      containers:
        - name: superexec-clientapp-10
          image: flwr_superexec:0.0.1
          imagePullPolicy: Never
          args:
            - "--insecure"
            - "--plugin-type"
            - "clientapp"
            - "--appio-api-address"
            - "supernode-10:9103"