apiVersion: v1
kind: Service
metadata:
  name: superlink
spec:
  selector:
    app: superlink
  ports:
    - name: exec
      port: 9091
    - name: node
      port: 9092
    - name: run
      port: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superlink
  template:
    metadata:
      labels:
        app: superlink
    spec:
      containers:
        - name: superlink
          image: flwr/superlink:1.31.0
          args: ["--insecure", "--isolation", "process"]
          ports:
            - containerPort: 9091
            - containerPort: 9092
            - containerPort: 9093